### PR TITLE
Adding CI and fixing up a readme

### PR DESCRIPTION
**Pull request by timheuer**
Adds a few things:
- [x] Adds a readme
- [x] Adds a 'deploy to azure' ARM template for resource creation option
- [x] adds VS code launch.json settings
- [x] adds devcontainer for Codespaces 
- [x] removes daily build servers for nuget packages
- [x] updates to use public Validation package version instead of daily

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks very much @timheuer! Sorry I didn't notice this PR before. For some reason I'm not subscribed for notifications on this repo so it's only by chance I saw it now.

All the changes you've made look good, apart from I'm not sure about the `deploy.*` ones. Could you clarify under what circumstances someone would need an ARM template? Wouldn't it be more normal to deploy to App Service via the portal, which doesn't need this template? My concern is that having this file might make Azure look more complicated than it is. TBH I suspect people wouldn't know how to create a `deploy.json` file like that, and would get intimidated about writing such a thing by hand in their own projects, so it might not be an ideal thing to include in an introductory sample.

**Comment by timheuer** [comment]
The ARM template and button on the readme help developers create their resources in one click. It presents the portal and asks you to provide a few names but is more single-click purpose. It helps people not have to navigate the portal. Any Azure sample should have this option.

**Comment by SteveSandersonMS** [comment]
OK, thanks for clarifying! I guess some people may be put off by the sense of that file being complex and alien, but perhaps this is outweighed by the benefit that others will be more likely to succeed with deployment.

**Comment by SteveSandersonMS** [comment]
Thanks again for adding this PR, by the way!

**Pull request merged**
